# Kubernetes alias shortcuts
alias k='kubectl'

# Kubernetes get command aliases
alias kg='kubectl get'
alias kgp='kubectl get pods'
alias kgd='kubectl get deployments'
alias kgs='kubectl get services'
alias kgcm='kubectl get configmaps'
alias kgss='kubectl get secrets'
alias kgn='kubectl get nodes'
alias kgns='kubectl get namespaces'
alias kgj='kubectl get jobs'
alias kgcj='kubectl get cronjobs'
alias kgr='kubectl get roles'
alias kgbr='kubectl get rolebindings'
alias kgcr='kubectl get clusterroles'
alias kgcrb='kubectl get clusterrolebindings'
alias kge='kubectl get events'


# Kubernetes describe command aliases
alias kd='kubectl describe'
alias kdp='kubectl describe pod'
alias kdd='kubectl describe deployment'
alias kds='kubectl describe service'
alias kdcm='kubectl describe configmap'
alias kdss='kubectl describe secret'
alias kdn='kubectl describe node'
alias kdns='kubectl describe namespace'
alias kdj='kubectl describe job'
alias kdcj='kubectl describe cronjob'
alias kdr='kubectl describe role'
alias kdbr='kubectl describe rolebinding'
alias kdcr='kubectl describe clusterrole'
alias kdcrb='kubectl describe clusterrolebinding'
alias kde='kubectl describe event'


# Kubernetes delete command aliases
alias kdel='kubectl delete'
alias kdelp='kubectl delete pod'
alias kdeld='kubectl delete deployment'
alias kdels='kubectl delete service'
alias kdelcm='kubectl delete configmap'
alias kdelss='kubectl delete secret'
alias kdeln='kubectl delete node'
alias kdelns='kubectl delete namespace'
alias kdelj='kubectl delete job'
alias kdelcj='kubectl delete cronjob'
alias kdelr='kubectl delete role'
alias kdelbr='kubectl delete rolebinding'
alias kdelcr='kubectl delete clusterrole'
alias kdelcrb='kubectl delete clusterrolebinding'


# Kubernetes create command aliases
alias kc='kubectl create'
alias kcp='kubectl create pod'
alias kcd='kubectl create deployment'
alias kcs='kubectl create service'
alias kccm='kubectl create configmap'
alias kcss='kubectl create secret'
alias kcn='kubectl create namespace'
alias kcj='kubectl create job'
alias kccj='kubectl create cronjob'
alias kcsr='kubectl create role'
alias kcbr='kubectl create rolebinding'
alias kcsr='kubectl create clusterrole'
alias kcrb='kubectl create clusterrolebinding'

# Administer
alias ka='kubectl apply -f'
alias kl='kubectl logs'
alias klf='kubectl logs -f'
alias kex='kubectl exec -it'
alias kctx='kubectl config use-context'
alias kctxg='kubectl config get-contexts'
alias kns='kubectl config set-context --current --namespace'
